[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ft_package"
version = "0.0.1"
description = "A simple test package"
readme = "README.md"
authors = [
    { name = "jopadova", email = "jopadova@student.42.fr" }
]
license = {text = "MIT"}